### ISSUE TITLE
Lerp vertices?

### ISSUE THREAD

**Issue by getwilde** [kema8351/radar-chart#1]
Thanks for the nice scripts!   I attempted to animate the parameters.  Mathf.Lerp does increment param values over time, but visually, the graphic vertices jump to the `init` position, and then don't move further. In other words, setting a Parameter[i] value only works once, then not subsequently over time??  Is there a way to lerp/animate the chart?

```	
        public IEnumerator SetRadarChartParam(RadarChart radar, int paramIndex, float init, float final)    
	{    
		float _current;   
		float dur = (final - init) / speed;   
		float t = 0f;   
		while (t < dur)   
		{   
			_current = Mathf.Lerp(init, final, t / dur);   
			radar.Parameters[paramIndex] = _current;   
			t += Time.deltaTime;   
			yield return null;    
		}    
		radar.Parameters[paramIndex] = final;    
	}    
```

**Comment by kema8351** [comment]
Thanks and sorry.
I realized this issue a short time ago.

Setting an array to the parameter field was necessary to animate the radar chart.
But, I felt inconvenience. I changed the script. Then new script can animate a radar chart when a single parameter is set.

```
    public IEnumerator SetRadarChartParam(RadarChart radar, int paramIndex, float init, float final)
    {
        float _current;
        float dur = (final - init) / speed;
        float t = 0f;
        while (t < dur)
        {
            _current = Mathf.Lerp(init, final, t / dur);
            radar.SetParameter(paramIndex, _current);
            t += Time.deltaTime;
            yield return null;
        }
        radar.SetParameter(paramIndex, final);
    }
```

Update radar chart script and try it.
